vendor: Kubernetes kOps Project
name: kOps
version: v1.24.0
website_url: https://kops.sigs.k8s.io
documentation_url: https://github.com/kubernetes/kops
product_logo_url: https://raw.githubusercontent.com/kubernetes/kops/master/docs/img/logo.svg
type: installer
description: 'kOps is open-source, community-maintained tooling for production-grade kubernetes cluster installation, management and upgrades'
