vendor: Nutanix
name: Karbon
version: v2.6.0
website_url: https://www.nutanix.com/products/karbon
documentation_url: https://portal.nutanix.com/page/documents/details/?targetId=Release-Notes-Karbon-v2_6_0%3ARelease-Notes-Karbon-v2_6_0
product_logo_url: https://www.nutanix.com/wp-content/uploads/2017/11/nutanix.png
type: hosted
description: "Managed Kubernetes offering by Nutanix."
