vendor: China Telecom Cloud Technology Co., Ltd.
name: Chinatelecom Cloud Edge Container Service for Kubernetes
version: v1.17.0
website_url: https://www.ctyun.cn/products/eck
repo_url:
documentation_url: https://www.ctyun.cn/document/10024899
product_logo_url: https://landscape.cncf.io/logos/china-telecom-cloud-technology-co-ltd-member.svg
type: hosted
description: "The Chinatelecom Cloud Edge Container Service for Kubernetes is a offering to allow customers to create and operator Kubernetes cluster builds on top of Chinatelecom Cloud resources."
contact_email_address: zhanglifang@chinatelecom.cn