vendor: OpenNebula Systems
name: OpenNebula Kubernetes Engine
version: v1.24
website_url: https://marketplace.opennebula.io/appliance/b5033eba-cd31-487e-892a-035cd70441ef
documentation_url: https://docs.opennebula.io/appliances/service/oneke.html
product_logo_url: https://opennebula.io/logo-blue.svg
type: Installer
description: Virtual Appliance for KVM and vCenter with preinstalled Kubernetes service available from OpenNebula's Public Marketplace.
