vendor: Scality
name: MetalK8s
description: "An opinionated Kubernetes distribution with a focus on long-term on-prem deployments"
version: 125.0
type: distribution
website_url: https://github.com/scality/metalk8s/
repo_url: https://github.com/scality/metalk8s.git
product_logo_url: https://raw.githubusercontent.com/scality/metalk8s/development/125.0/artwork/metalk8s-logo-vertical.svg
documentation_url: https://metal-k8s.readthedocs.io/en/development-125.0/
contact_email_address: squad-metalk8s@scality.com
