vendor: Flant
name: Deckhouse Installer (DHCTL)
version: v1.37.5
website_url: https://github.com/deckhouse/deckhouse
repo_url: https://github.com/deckhouse/deckhouse
documentation_url: https://deckhouse.io/en/documentation/v1/installing/
product_logo_url: https://deckhouse.io/images/logos/deckhouse-platform.svg
type: installer
description: 'Deckhouse Installer (DHCTL) is an application for creating Kubernetes clusters and configuring their infrastructure.'
